cosmocli:
  env:
    # COSMOCLI_COSMOSDB_ACCOUNT_ENDPOINT: ""
    # COSMOCLI_COSMOSDB_ACCOUNT_KEY: ""
    # COSMOCLI_COSMOSDB_REJECT_UNAUTHORIZED: ""
    COSMOCLI_COSMOSDB_USE_KEYVAULT: "true"
    COSMOCLI_KEYVAULT_NAME: "keyvault-name"
    # COSMOCLI_COSMOSDB_ENDPOINT_SECRET_NAME: ""
    # COSMOCLI_COSMOSDB_KEY_SECRET_NAME: ""
    COSMOCLI_STORAGE_ACCOUNT_NAME_SECRET_NAME: "StorageAccountName"
    COSMOCLI_STORAGE_ACCOUNT_KEY_SECRET_NAME: "StorageAccountKey"
    # COSMOCLI_STORAGE_ACCOUNT_NAME: ""
    COSMOCLI_STORAGE_ACCOUNT_CONTAINER: "cosmosdb-backup"
    # COSMOCLI_STORAGE_ACCOUNT_KEY: ""
    # COSMOCLI_STORAGE_ACCOUNT_PREFIX: ""
    # COSMOCLI_STORAGE_ACCOUNT_SUFFIX: ""
    # COSMOCLI_STORAGE_ACCOUNT_DELIMITER: ""
    # COSMOCLI_STORAGE_ACCOUNT_PROTOCOL: ""
    # COSMOCLI_STORAGE_ACCOUNT_CONNECTIONSTRING_SUFFIX: ""
    COSMOCLI_STORAGE_ACCOUNT_USE_KEYVAULT: "true"
    COSMOCLI_STORAGE_ACCOUNT_USE_DATAFACTORY_FORMAT: "true"
    # COSMOCLI_FILESYSTEM_PATH: ""
    # COSMOCLI_FILESYSTEM_PREFIX: ""
    # COSMOCLI_FILESYSTEM_SUFFIX: ""
    # COSMOCLI_FILESYSTEM_DELIMITER: ""

image:
  repository: quay.io/xenitab/node-cosmocli
  pullPolicy: IfNotPresent
  tag: ""

job:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Replace
  restartPolicy: OnFailure
  containerArgs:
    - backup
    - azure-storage-account
  startingDeadlineSeconds: 200
  extraPodLabels: {}
    # aadpodidbinding: msi

nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

resources:
  # limits:
  #   memory: 4096Mi
  requests:
    cpu: 500m
    memory: 256Mi

nodeSelector: {}

tolerations: {}

affinity: {}
