apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "node-cosmocli.fullname" . }}
  labels:
    {{- include "node-cosmocli.labels" . | nindent 4 }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  schedule: {{ .Values.job.schedule | quote }}
  concurrencyPolicy: {{ .Values.job.concurrencyPolicy | quote }}
  startingDeadlineSeconds: {{ .Values.job.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "node-cosmocli.selectorLabels" . | nindent 12 }}
          {{- range $key, $value := .Values.job.extraPodLabels }}
            {{ $key }}: {{ $value | quote }}
          {{- end }}
        spec:
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              args: 
{{- range .Values.job.containerArgs }}
                - {{ . | quote }}
{{- end }}
              command: 
{{- range .Values.job.containerCommand }}
                - {{ . | quote }}
{{- end }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              env:
              {{- range $key, $value := .Values.cosmocli.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
              {{- end }}
          restartPolicy: {{ .Values.job.restartPolicy | quote }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}